code --install-extension DavidAnson.vscode-markdownlint
code --install-extension Equinusocio.vsc-material-theme
code --install-extension Mukundan.python-docs
code --install-extension Orta.vscode-jest
code --install-extension PeterJausovec.vscode-docker
code --install-extension azaugg.vscode-python-docstring
code --install-extension bbenoist.vagrant
code --install-extension bierner.lit-html
code --install-extension christian-kohler.npm-intellisense
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension dbaeumer.vscode-eslint
code --install-extension eamodio.gitlens
code --install-extension eg2.vscode-npm-script
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.auto-close-tag
code --install-extension GrapeCity.gc-excelviewer
code --install-extension josa.markdown-table-formatter
code --install-extension ms-python.python
code --install-extension ms-vscode.Go
code --install-extension naumovs.color-highlight
code --install-extension pranaygp.vscode-css-peek
code --install-extension robertohuertasm.vscode-icons
code --install-extension shyykoserhiy.vscode-spotify
code --install-extension steoates.autoimport
code --install-extension stevencl.addDocComments
code --install-extension tht13.python
code --install-extension vincaslt.highlight-matching-tag
